name: Makefile CI

on:
  push:
    branches: [ master, test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: run
      run: bash build/redis.sh
